name: satu_ayat_sehari_android
description: A daily devotional Flutter app.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter

    # UI & Icons
    cupertino_icons: ^1.0.8
    flutter_animate: ^4.5.0

    # Utilities
    uuid: ^4.3.3
    shared_preferences: ^2.2.2
    flutter_dotenv: ^5.1.0
    intl:
        ^0.19.0

        # LOCAL STORAGE
    sqflite: ^2.3.3
    path: ^1.9.0

    # Backend / Services
    supabase_flutter: ^2.3.4

    # Firebase
    firebase_core: ^2.25.4
    firebase_messaging: ^14.7.10

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/images/logo_app.png
